### PR TITLE
cmake: Fix OpenGL linking

### PR DESCRIPTION
**Pull request by lanodan**
This fixes building on Linux with libOpenGL (GLVND-specific) instead of libGL (legacy, GLX-specific)

### CODE REVIEW

**Comment by lanodan** [comment]
Not sure why the Windows build is failing, it shoudl just work.

And getting a Windows Development environment is way too painful so I'll just partly revert the `if(WIN32)` clause.

**Comment by sezero** [comment]
Running on i686-linux, using cmake-3.9.6, I see: `-- Found OpenGL: /usr/lib/libGL.so`
but in CMakeFiles/testgl.dir/link.txt there is no libGL linkage. And obviously linkage fails
for me:
```
CMakeFiles/testgl.dir/test/testgl.c.o: In function `SDL_GL_LoadTexture':
testgl.c:(.text+0x332): undefined reference to `glGenTextures'
testgl.c:(.text+0x345): undefined reference to `glBindTexture'
testgl.c:(.text+0x361): undefined reference to `glTexParameteri'
testgl.c:(.text+0x37d): undefined reference to `glTexParameteri'
testgl.c:(.text+0x3c3): undefined reference to `glTexImage2D'
CMakeFiles/testgl.dir/test/testgl.c.o: In function `SDL_GL_Leave2DMode':
testgl.c:(.text+0x46e): undefined reference to `glMatrixMode'
testgl.c:(.text+0x473): undefined reference to `glPopMatrix'
testgl.c:(.text+0x47f): undefined reference to `glMatrixMode'
testgl.c:(.text+0x484): undefined reference to `glPopMatrix'
CMakeFiles/testgl.dir/test/testgl.c.o: In function `SDL_GL_Enter2DMode':
testgl.c:(.text+0x4a6): undefined reference to `glPushAttrib'
testgl.c:(.text+0x4b2): undefined reference to `glDisable'
testgl.c:(.text+0x4be): undefined reference to `glDisable'
testgl.c:(.text+0x4ca): undefined reference to `glEnable'
testgl.c:(.text+0x4d6): undefined reference to `glEnable'
testgl.c:(.text+0x4ea): undefined reference to `glBlendFunc'
testgl.c:(.text+0x50c): undefined reference to `glViewport'
testgl.c:(.text+0x518): undefined reference to `glMatrixMode'
testgl.c:(.text+0x51d): undefined reference to `glPushMatrix'
testgl.c:(.text+0x522): undefined reference to `glLoadIdentity'
testgl.c:(.text+0x548): undefined reference to `glOrtho'
testgl.c:(.text+0x554): undefined reference to `glMatrixMode'
testgl.c:(.text+0x559): undefined reference to `glPushMatrix'
testgl.c:(.text+0x55e): undefined reference to `glLoadIdentity'
testgl.c:(.text+0x57a): undefined reference to `glTexEnvf'
CMakeFiles/testgl.dir/test/testgl.c.o: In function `DrawLogoTexture':
testgl.c:(.text+0x87c): undefined reference to `glBindTexture'
testgl.c:(.text+0x888): undefined reference to `glBegin'
testgl.c:(.text+0x89e): undefined reference to `glTexCoord2f'
testgl.c:(.text+0x8b4): undefined reference to `glVertex2i'
testgl.c:(.text+0x8ca): undefined reference to `glTexCoord2f'
testgl.c:(.text+0x8e6): undefined reference to `glVertex2i'
testgl.c:(.text+0x8fc): undefined reference to `glTexCoord2f'
testgl.c:(.text+0x918): undefined reference to `glVertex2i'
testgl.c:(.text+0x92e): undefined reference to `glTexCoord2f'
testgl.c:(.text+0x950): undefined reference to `glVertex2i'
testgl.c:(.text+0x955): undefined reference to `glEnd'
testgl.c:(.text+0x961): undefined reference to `glMatrixMode'
testgl.c:(.text+0x966): undefined reference to `glPopMatrix'
testgl.c:(.text+0x972): undefined reference to `glMatrixMode'
testgl.c:(.text+0x977): undefined reference to `glPopMatrix'
testgl.c:(.text+0x97c): undefined reference to `glPopAttrib'
CMakeFiles/testgl.dir/test/testgl.c.o: In function `DrawLogoCursor':
testgl.c:(.text+0xb69): undefined reference to `glBindTexture'
testgl.c:(.text+0xb75): undefined reference to `glBegin'
testgl.c:(.text+0xb8b): undefined reference to `glTexCoord2f'
testgl.c:(.text+0xb9d): undefined reference to `glVertex2i'
testgl.c:(.text+0xbb3): undefined reference to `glTexCoord2f'
testgl.c:(.text+0xbca): undefined reference to `glVertex2i'
testgl.c:(.text+0xbe0): undefined reference to `glTexCoord2f'
testgl.c:(.text+0xbf7): undefined reference to `glVertex2i'
testgl.c:(.text+0xc0d): undefined reference to `glTexCoord2f'
testgl.c:(.text+0xc29): undefined reference to `glVertex2i'
testgl.c:(.text+0xc2e): undefined reference to `glEnd'
testgl.c:(.text+0xc3a): undefined reference to `glMatrixMode'
testgl.c:(.text+0xc3f): undefined reference to `glPopMatrix'
testgl.c:(.text+0xc4b): undefined reference to `glMatrixMode'
testgl.c:(.text+0xc50): undefined reference to `glPopMatrix'
testgl.c:(.text+0xc55): undefined reference to `glPopAttrib'
CMakeFiles/testgl.dir/test/testgl.c.o: In function `RunGLTest':
testgl.c:(.text+0xe2f): undefined reference to `glGetString'
testgl.c:(.text+0xe4b): undefined reference to `glGetString'
testgl.c:(.text+0xe67): undefined reference to `glGetString'
testgl.c:(.text+0xe83): undefined reference to `glGetString'
testgl.c:(.text+0xfe0): undefined reference to `glViewport'
testgl.c:(.text+0xfec): undefined reference to `glMatrixMode'
testgl.c:(.text+0xff1): undefined reference to `glLoadIdentity'
testgl.c:(.text+0x1027): undefined reference to `glOrtho'
testgl.c:(.text+0x1033): undefined reference to `glMatrixMode'
testgl.c:(.text+0x1038): undefined reference to `glLoadIdentity'
testgl.c:(.text+0x1044): undefined reference to `glEnable'
testgl.c:(.text+0x1050): undefined reference to `glDepthFunc'
testgl.c:(.text+0x105c): undefined reference to `glShadeModel'
testgl.c:(.text+0x1098): undefined reference to `glClearColor'
testgl.c:(.text+0x10a4): undefined reference to `glClear'
testgl.c:(.text+0x10b0): undefined reference to `glBegin'
testgl.c:(.text+0x10be): undefined reference to `glColor3fv'
testgl.c:(.text+0x10cc): undefined reference to `glVertex3fv'
testgl.c:(.text+0x10da): undefined reference to `glColor3fv'
testgl.c:(.text+0x10e2): undefined reference to `glVertex3fv'
testgl.c:(.text+0x10ed): undefined reference to `glColor3fv'
testgl.c:(.text+0x10fb): undefined reference to `glVertex3fv'
testgl.c:(.text+0x1106): undefined reference to `glColor3fv'
testgl.c:(.text+0x1114): undefined reference to `glVertex3fv'
testgl.c:(.text+0x111f): undefined reference to `glColor3fv'
testgl.c:(.text+0x112d): undefined reference to `glVertex3fv'
testgl.c:(.text+0x1138): undefined reference to `glColor3fv'
testgl.c:(.text+0x1146): undefined reference to `glVertex3fv'
testgl.c:(.text+0x1151): undefined reference to `glColor3fv'
testgl.c:(.text+0x115f): undefined reference to `glVertex3fv'
testgl.c:(.text+0x116a): undefined reference to `glColor3fv'
testgl.c:(.text+0x1178): undefined reference to `glVertex3fv'
testgl.c:(.text+0x1186): undefined reference to `glColor3fv'
testgl.c:(.text+0x1194): undefined reference to `glVertex3fv'
testgl.c:(.text+0x119f): undefined reference to `glColor3fv'
testgl.c:(.text+0x11ad): undefined reference to `glVertex3fv'
testgl.c:(.text+0x11b8): undefined reference to `glColor3fv'
testgl.c:(.text+0x11c6): undefined reference to `glVertex3fv'
testgl.c:(.text+0x11d4): undefined reference to `glColor3fv'
testgl.c:(.text+0x11dc): undefined reference to `glVertex3fv'
testgl.c:(.text+0x11e7): undefined reference to `glColor3fv'
testgl.c:(.text+0x11f5): undefined reference to `glVertex3fv'
testgl.c:(.text+0x1200): undefined reference to `glColor3fv'
testgl.c:(.text+0x120e): undefined reference to `glVertex3fv'
testgl.c:(.text+0x1219): undefined reference to `glColor3fv'
testgl.c:(.text+0x1227): undefined reference to `glVertex3fv'
testgl.c:(.text+0x1232): undefined reference to `glColor3fv'
testgl.c:(.text+0x1240): undefined reference to `glVertex3fv'
testgl.c:(.text+0x124b): undefined reference to `glColor3fv'
testgl.c:(.text+0x1259): undefined reference to `glVertex3fv'
testgl.c:(.text+0x1267): undefined reference to `glColor3fv'
testgl.c:(.text+0x1275): undefined reference to `glVertex3fv'
testgl.c:(.text+0x1280): undefined reference to `glColor3fv'
testgl.c:(.text+0x128e): undefined reference to `glVertex3fv'
testgl.c:(.text+0x1299): undefined reference to `glColor3fv'
testgl.c:(.text+0x12a7): undefined reference to `glVertex3fv'
testgl.c:(.text+0x12b2): undefined reference to `glColor3fv'
testgl.c:(.text+0x12c0): undefined reference to `glVertex3fv'
testgl.c:(.text+0x12ce): undefined reference to `glColor3fv'
testgl.c:(.text+0x12d6): undefined reference to `glVertex3fv'
testgl.c:(.text+0x12e1): undefined reference to `glColor3fv'
testgl.c:(.text+0x12ef): undefined reference to `glVertex3fv'
testgl.c:(.text+0x12fa): undefined reference to `glColor3fv'
testgl.c:(.text+0x1308): undefined reference to `glVertex3fv'
testgl.c:(.text+0x130d): undefined reference to `glEnd'
testgl.c:(.text+0x1319): undefined reference to `glMatrixMode'
testgl.c:(.text+0x133d): undefined reference to `glRotatef'
testgl.c:(.text+0x136c): undefined reference to `glGetError'
testgl.c:(.text+0x1445): undefined reference to `glDeleteTextures'
testgl.c:(.text+0x155c): undefined reference to `glDeleteTextures'
CMakeFiles/testgl.dir/test/testgl.c.o: In function `SDL_GL_Leave2DMode':
testgl.c:(.text+0x48a): undefined reference to `glPopAttrib'
collect2: ld returned 1 exit status
make[2]: *** [testgl] Error 1
make[1]: *** [CMakeFiles/testgl.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by lanodan** [comment]
@sezero Should be fixed now.

**Comment by sezero** [comment]
> @sezero Should be fixed now.

Confirmed, thanks.

**Comment by sezero** [comment]
@icculus: Should we merge this?

**Comment by Conan-Kudo** [comment]
@sezero, @icculus It'd be great if this was merged. 👍🏾

**Comment by icculus** [comment]
I think we should just bump cmake_minimum_required to 3.1.0 and remove the check in the middle, fwiw.

**Comment by sezero** [comment]
> I think we should just bump cmake_minimum_required to 3.1.0 and remove the check in the middle, fwiw.

It's not `3.1.0` but `3.10`.  I'd say it would be overkill, but whatever.
Long live Makefiles and autotools :)

**Pull request merged**
